sudo: required

language: cpp

services:
  - docker

script:
  - sudo docker build -f Dockerfile.ubuntu16 -t vss-core-ubuntu16 .
  - sudo docker run vss-core-ubuntu16 test
  - sudo docker build -f Dockerfile.debian9 -t vss-core-debian9 .
  - sudo docker run vss-core-debian9 test
  - sudo docker build -f Dockerfile.ubuntu18 -t vss-core-ubuntu18 .
  - sudo docker run vss-core-ubuntu18 test

notifications:
  slack: vss-sdk:1bwlO40eKoIRA7l5yjLNqmjD